#
# MIT License
#
# Copyright (c) 2023 Mike Heddes, Igor Nunes, Pere Vergés, Denis Kleyko, and Danny Abraham
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.
#
r"""Deterministic PRNG generators matching FPGA/ASIC RTL implementations.

For bit-accurate golden-model verification, the hypervectors generated by
torchhd must be identical to those produced by the RTL's PRNG at boot time.
This module provides software implementations of the common hardware PRNG
architectures used in HDC accelerators:

* **Galois LFSR** — parametrized by polynomial, width, and seed.
* **XORSHIFT** — fast 32/64-bit xorshift with configurable shifts.

Each generator exposes a PyTorch-compatible interface and can produce
``torchhd.random()``-compatible hypervectors that are bit-identical to
the corresponding Verilog module output.

Classes
-------
LFSR
    Galois (one-to-many) linear-feedback shift register.
XORShift32
    Marsaglia 32-bit xorshift PRNG.
XORShift64
    Marsaglia 64-bit xorshift PRNG.

Functions
---------
export_lfsr_verilog
    Emit a synthesizable Verilog LFSR module matching the Python instance.
"""

from typing import Optional, Literal, Tuple
import torch
from torch import Tensor


__all__ = [
    "LFSR",
    "XORShift32",
    "XORShift64",
    "export_lfsr_verilog",
]


# Known good LFSR polynomials (maximal-length for given width)
LFSR_POLYNOMIALS = {
    # width: (tap_positions in the Galois config, taps are XOR'd with LSB)
    8: 0xB4,       # x^8 + x^6 + x^5 + x^4 + 1
    10: 0x240,     # x^10 + x^7 + 1
    12: 0x829,     # x^12 + x^11 + x^8 + x^6 + 1
    16: 0x8016,    # x^16 + x^15 + x^13 + x^4 + 1
    24: 0x80001B,  # x^24 + x^23 + x^22 + x^17 + 1
    32: 0x80000062,  # x^32 + x^31 + x^30 + x^10 + 1
}


class LFSR:
    r"""Galois (one-to-many) linear-feedback shift register.

    Implements the standard LFSR architecture used in FPGA projects:
    at each step the LSB is extracted as output, then the register is
    shifted right by one and, if the output bit was 1, the taps are XOR'd
    into the high bits.

    This is bit-identical to the common Verilog pattern:

    .. code-block:: systemverilog

        assign out = lfsr[0];
        always @(posedge clk) begin
          lfsr <= {1'b0, lfsr[W-1:1]} ^ ({W{out}} & POLY);
        end

    Args:
        width: LFSR width in bits (8, 16, 24, or 32).
        polynomial: Taps as a bitmask.  If ``None``, a maximal-length
            polynomial is selected for the given width.
        seed: Initial state.  If ``None``, uses ``1``.
        output_mode: ``"lsb"`` extracts LSB each cycle (default hardware
            style); ``"serial"`` shifts out the full register width in
            ``width`` cycles; ``"parallel"`` returns the entire register.

    Examples::

        >>> lfsr = LFSR(width=16)
        >>> bits = [lfsr.next() for _ in range(8)]
        >>> len(bits)
        8
    """

    width: int
    polynomial: int
    state: int
    output_mode: str

    def __init__(
        self,
        width: int = 16,
        polynomial: Optional[int] = None,
        seed: Optional[int] = None,
        output_mode: Literal["lsb", "serial", "parallel"] = "lsb",
    ) -> None:
        if polynomial is None:
            if width not in LFSR_POLYNOMIALS:
                raise ValueError(
                    f"No default polynomial for width={width}. "
                    f"Known widths: {list(LFSR_POLYNOMIALS.keys())}. "
                    f"Provide a polynomial manually."
                )
            polynomial = LFSR_POLYNOMIALS[width]

        if seed is None:
            seed = 1

        self.width = width
        self.polynomial = polynomial & ((1 << width) - 1)
        self.state = seed & ((1 << width) - 1)
        self.output_mode = output_mode

        if self.state == 0:
            raise ValueError("LFSR seed must be non-zero (state 0 is a lock-up state)")

    def next(self) -> int:
        """Advance one step and return the output bit (0 or 1)."""
        out = self.state & 1
        feedback = self.polynomial if out else 0
        self.state = (self.state >> 1) ^ feedback
        return out

    def next_byte(self) -> int:
        """Advance 8 steps and return an 8-bit value (LSB-first serial output)."""
        val = 0
        for i in range(8):
            val |= self.next() << i
        return val

    def next_int(self) -> int:
        """Advance ``width`` steps and return a ``width``-bit value (serial output)."""
        val = 0
        for i in range(self.width):
            val |= self.next() << i
        return val

    def next_parallel(self) -> int:
        """Return the entire LFSR state (parallel output), then advance 1 step."""
        val = self.state
        self.next()
        return val

    def next_tensor(
        self,
        num_vectors: int,
        dimensions: int,
        *,
        mode: Literal["bipolar", "binary"] = "bipolar",
        device=None,
    ) -> Tensor:
        r"""Generate ``num_vectors`` hypervectors of ``dimensions`` dimensions.

        Uses the LFSR to produce a deterministic stream of bits that are
        packed into hypervectors.

        Args:
            num_vectors: Number of hypervectors to generate.
            dimensions: Dimensionality of each hypervector.
            mode: ``"bipolar"`` produces {−1, +1}, ``"binary"`` produces {0, 1}.
            device: Desired torch device.

        Returns:
            Tensor of shape ``(num_vectors, dimensions)`` with ``dtype``
            ``torch.int8`` (bipolar) or ``torch.uint8`` (binary).
        """
        total_bits = num_vectors * dimensions
        if mode == "bipolar":
            data = torch.zeros(total_bits, dtype=torch.int8, device=device)
            for i in range(total_bits):
                data[i] = 1 if self.next() else -1
        else:
            data = torch.zeros(total_bits, dtype=torch.uint8, device=device)
            for i in range(total_bits):
                data[i] = self.next()
        return data.reshape(num_vectors, dimensions)

    def __repr__(self) -> str:
        return (
            f"LFSR(width={self.width}, poly=0x{self.polynomial:0{self.width//4}x}, "
            f"state=0x{self.state:0{self.width//4}x})"
        )


class XORShift32:
    r"""Marsaglia 32-bit xorshift PRNG.

    A lightweight, fast PRNG often used in RTL for HDC accelerators because
    it maps to three XOR/shift operations and uses minimal LUT resources.

    The state is updated as:

    .. code-block:: text

        x ^= x << 13;
        x ^= x >> 17;
        x ^= x << 5;

    Args:
        seed: Initial 32-bit seed (non-zero).  Default: ``2463534242``.

    Examples::

        >>> rng = XORShift32(seed=12345)
        >>> rng.next()
        3701687786
    """

    state: int

    def __init__(self, seed: int = 2463534242) -> None:
        if seed == 0:
            raise ValueError("Seed must be non-zero")
        self.state = seed & 0xFFFFFFFF

    def next(self) -> int:
        """Return the next 32-bit random value."""
        x = self.state
        x ^= (x << 13) & 0xFFFFFFFF
        x ^= (x >> 17)
        x ^= (x << 5) & 0xFFFFFFFF
        self.state = x
        return x

    def next_bit(self) -> int:
        """Return a single random bit (0 or 1) by extracting LSB."""
        return self.next() & 1

    def next_tensor(
        self,
        num_vectors: int,
        dimensions: int,
        *,
        mode: Literal["bipolar", "binary"] = "bipolar",
        device=None,
    ) -> Tensor:
        r"""Generate hypervectors deterministically.

        Args:
            num_vectors: Number of hypervectors.
            dimensions: Dimensionality per hypervector.
            mode: ``"bipolar"`` or ``"binary"``.
            device: Desired torch device.

        Returns:
            Tensor of shape ``(num_vectors, dimensions)``.
        """
        total_bits = num_vectors * dimensions
        if mode == "bipolar":
            data = torch.zeros(total_bits, dtype=torch.int8, device=device)
        else:
            data = torch.zeros(total_bits, dtype=torch.uint8, device=device)

        for i in range(0, total_bits, 32):
            word = self.next()
            end = min(i + 32, total_bits)
            for j in range(i, end):
                data[j] = 1 if (word & 1) else (-1 if mode == "bipolar" else 0)
                word >>= 1

        return data.reshape(num_vectors, dimensions)

    def __repr__(self) -> str:
        return f"XORShift32(state=0x{self.state:08x})"


class XORShift64:
    r"""Marsaglia 64-bit xorshift PRNG.

    Same algorithm as :class:`XORShift32` but for 64-bit state:

    .. code-block:: text

        x ^= x << 13;
        x ^= x >> 7;
        x ^= x << 17;

    Args:
        seed: Initial 64-bit seed (non-zero).  Default: ``88172645463325252``.

    Examples::

        >>> rng = XORShift64(seed=12345)
        >>> rng.next()
        13219153759679143922
    """

    state: int

    def __init__(self, seed: int = 88172645463325252) -> None:
        if seed == 0:
            raise ValueError("Seed must be non-zero")
        self.state = seed & 0xFFFFFFFFFFFFFFFF

    def next(self) -> int:
        """Return the next 64-bit random value."""
        x = self.state
        x ^= (x << 13) & 0xFFFFFFFFFFFFFFFF
        x ^= (x >> 7)
        x ^= (x << 17) & 0xFFFFFFFFFFFFFFFF
        self.state = x
        return x

    def next_bit(self) -> int:
        """Return a single random bit."""
        return self.next() & 1

    def next_tensor(
        self,
        num_vectors: int,
        dimensions: int,
        *,
        mode: Literal["bipolar", "binary"] = "bipolar",
        device=None,
    ) -> Tensor:
        r"""Generate hypervectors deterministically.

        Args:
            num_vectors: Number of hypervectors.
            dimensions: Dimensionality per hypervector.
            mode: ``"bipolar"`` or ``"binary"``.
            device: Desired torch device.

        Returns:
            Tensor of shape ``(num_vectors, dimensions)``.
        """
        total_bits = num_vectors * dimensions
        if mode == "bipolar":
            data = torch.zeros(total_bits, dtype=torch.int8, device=device)
        else:
            data = torch.zeros(total_bits, dtype=torch.uint8, device=device)

        for i in range(0, total_bits, 64):
            word = self.next()
            end = min(i + 64, total_bits)
            for j in range(i, end):
                data[j] = 1 if (word & 1) else (-1 if mode == "bipolar" else 0)
                word >>= 1

        return data.reshape(num_vectors, dimensions)

    def __repr__(self) -> str:
        return f"XORShift64(state=0x{self.state:016x})"


# ---------------------------------------------------------------------------
# Verilog export for LFSR
# ---------------------------------------------------------------------------

def export_lfsr_verilog(
    lfsr: LFSR,
    filepath: str,
    *,
    module_name: str = "lfsr",
    clk_name: str = "clk",
    rst_name: str = "rst_n",
    en_name: str = "en",
    out_name: str = "out",
) -> None:
    r"""Export a synthesizable Verilog LFSR module matching the Python instance.

    The generated module is a standard Galois LFSR that, when reset and clocked
    identically, produces the same output bitstream as the Python :class:`LFSR`.

    Args:
        lfsr: The Python LFSR instance to export.
        filepath: Output ``.v`` file path.
        module_name: Verilog module name.
        clk_name: Clock signal name.
        rst_name: Reset signal name (active low).
        en_name: Enable signal name.
        out_name: Output bit signal name.
    """
    width = lfsr.width
    poly = lfsr.polynomial
    seed = lfsr.state  # current state (or original seed would be saved)

    # Format the polynomial as a bit string for readability
    poly_bits = f"{poly:0{width}b}"

    lines = []
    lines.append("// Auto-generated Galois LFSR")
    lines.append(f"// Width: {width}, Polynomial: 0x{poly:0{width//4}x}")
    lines.append(f"// Seed: 0x{seed:0{width//4}x}")
    lines.append("")
    lines.append(f"module {module_name} (")
    lines.append(f"  input  wire        {clk_name},")
    lines.append(f"  input  wire        {rst_name},")
    lines.append(f"  input  wire        {en_name},")
    lines.append(f"  output wire        {out_name}")
    lines.append(");")
    lines.append("")
    lines.append(f"  reg [{width-1}:0] lfsr_state;")
    lines.append("")
    lines.append(f"  assign {out_name} = lfsr_state[0];")
    lines.append("")
    lines.append(f"  always @(posedge {clk_name} or negedge {rst_name}) begin")
    lines.append(f"    if (!{rst_name}) begin")
    lines.append(f"      lfsr_state <= {width}'h{seed:0{(width+3)//4}x};")
    lines.append(f"    end else if ({en_name}) begin")
    lines.append(f"      if (lfsr_state[0])")
    lines.append(f"        lfsr_state <= (lfsr_state >> 1) ^ {width}'h{poly:0{(width+3)//4}x};")
    lines.append(f"      else")
    lines.append(f"        lfsr_state <= lfsr_state >> 1;")
    lines.append(f"    end")
    lines.append(f"  end")
    lines.append("")
    lines.append(f"endmodule")

    with open(filepath, "w") as f:
        f.write("\n".join(lines) + "\n")